In [66]:
import numpy as np

In [67]:
np.__version__

'1.26.4'

In [68]:
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [69]:
arr1.shape

(9,)

In [70]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [71]:
arr1[4]

48

In [72]:
arr1[1:4]

array([21, 32, 43])

In [73]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [74]:
indices = [1,2,5,6]

In [75]:
arr1[indices]

array([21, 32, 15, 76])

In [76]:
mask = (arr1 % 2 == 0)

In [77]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [78]:
arr1[mask]

array([10, 32, 48, 76])

In [79]:
arr1[0] = 100

In [80]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [81]:
arr2 = np.array([1, 2, 3, 4, 5])

In [82]:
print(arr2)

[1 2 3 4 5]


In [83]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [84]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [85]:
arr3 = np.arange(0, 50, 5)

In [86]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [87]:
np.shape(arr3)

(10,)

In [88]:
print(arr3.dtype)

int32


In [89]:
arr4 = np.zeros(10)

In [90]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [91]:
arr5 = np.eye(3)

In [92]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
arr6 = np.diag(np.array([1,2,3,4]))

In [94]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [95]:
arr7 = np.array([True, False, False, True])

In [96]:
print(arr7)

[ True False False  True]


In [97]:
arr8 = np.array(['True', 'False', 'False', 'True'])

In [98]:
print(arr8)

['True' 'False' 'False' 'True']


In [99]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [100]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [101]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


MATRIZES

In [103]:
arr9 = np.array([[1,2,3],[4,5,6]])

In [104]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [105]:
np.shape(arr9)

(2, 3)

In [118]:
arr10 = np.ones((2,3))

In [119]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [110]:
lista = [[13,81,22],[0,34,59],[21,48,94]]
arr11 = np.matrix(lista)
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [111]:
np.shape(arr11)

(3, 3)

In [112]:
arr11.size

9

In [113]:
arr11[2,1]

48

In [115]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [122]:
arr11.itemsize
arr11.nbytes
arr11.ndim

2

MATRIZ DE 3 DIMENSÕES

In [123]:
arr_3d = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])

In [124]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [125]:
arr_3d.ndim

3

In [126]:
arr_3d.shape

(2, 3, 4)

In [127]:
arr_3d[0, 2, 1]

10

MATRIZ DE 4 DIMENSÕES

In [128]:
arr_4d = np.array([
    [
        [
            [1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]
        ],
        [
            [21,22,23,24,25],
            [26,27,28,29,30],
            [31,32,33,34,35],
            [36,37,38,39,40]
        ],
        [
            [41,42,43,44,45],
            [46,47,48,49,50],
            [51,52,53,54,55],
            [56,57,58,59,60]
        ]
    ],
    [
        [
            [61,62,63,64,65],
            [66,67,68,69,70],
            [71,72,73,74,75],
            [76,77,78,79,80]
        ],
        [
            [81,82,83,84,85],
            [86,87,88,89,90],
            [91,92,93,94,95],
            [96,97,98,99,100]
        ],
        [
            [101,102,103,104,105],
            [106,107,108,109,110],
            [111,112,113,114,115],
            [116,117,118,119,120]
        ]   
    ]
])

In [129]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [130]:
arr_4d.ndim

4

In [131]:
arr_4d.shape

(2, 3, 4, 5)

In [133]:
arr_4d[1,2,3,]

array([116, 117, 118, 119, 120])

In [134]:
arr_4d[0,2,1,3]

49

MANIPULANDO ARQUIVOS COM NUMPY

In [135]:
import os
filename = os.path.join('dataset.csv')